"""madplan

Revision ID: 02e23c31eda1
Revises: 7c572d0741ab
Create Date: 2026-09-29 09:58:14.617643
"""

from alembic import op
import sqlalchemy as sa


revision = '02e23c31eda1'
down_revision = '7c572d0741ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_start_date'), ['start_date'], unique=False)

    op.create_table('plan_meal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('for_child', sa.Boolean(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('leftover_from_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['leftover_from_id'], ['plan_meal.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'date', 'for_child')
    )
    with op.batch_alter_table('plan_meal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_meal_plan_id'), ['plan_id'], unique=False)

    op.create_table('wishlist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wishlist_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishlist_item_plan_id'), ['plan_id'], unique=False)

    op.create_table('plan_line_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['recipe_ingredient.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meal_id'], ['plan_meal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meal_id', 'line_id')
    )
    with op.batch_alter_table('plan_line_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_line_state_meal_id'), ['meal_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_line_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_line_state_meal_id'))

    op.drop_table('plan_line_state')
    with op.batch_alter_table('wishlist_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlist_item_plan_id'))

    op.drop_table('wishlist_item')
    with op.batch_alter_table('plan_meal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_meal_plan_id'))

    op.drop_table('plan_meal')
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_start_date'))

    op.drop_table('plan')
    # ### end Alembic commands ###
