"""indkøbsliste

Revision ID: 6d48ea6937c8
Revises: 02e23c31eda1
Create Date: 2026-09-29 10:48:22.457886
"""

from alembic import op
import sqlalchemy as sa


revision = '6d48ea6937c8'
down_revision = '02e23c31eda1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('shopping_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('updated_ms', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'key')
    )
    with op.batch_alter_table('shopping_check', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shopping_check_plan_id'), ['plan_id'], unique=False)

    op.create_table('shopping_extra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('updated_ms', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping_extra')
    with op.batch_alter_table('shopping_check', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shopping_check_plan_id'))

    op.drop_table('shopping_check')
    op.drop_table('setting')
    # ### end Alembic commands ###
